export const robots=[
    {
        id:1,
        name:"Sonu",
        username:'Bret',
        emai:'s@gmail.com'
    },
    {
        id:2,
        name:"Annu",
        username:'Anto',
        emai:'a@gmail.com'
    },
    {
        id:3,
        name:"Arav",
        username:'clem',
        emai:'c@gmail.com'
    },
    {
        id:4,
        name:"Ram",
        username:'Pat',
        emai:'r@gmail.com'
    },
    {
        id:5,
        name:"Shyam",
        username:'Rat',
        emai:'sh@gmail.com'
    },
    {
        id:6,
        name:"Akhilesh",
        username:'Akhi',
        emai:'akh@gmail.com'
    },
    {
        id:7,
        name:"Ajay",
        username:'aaat',
        emai:'ajay@gmail.com'
    },
    {
        id:8,
        name:"Salman",
        username:'slat',
        emai:'sal@gmail.com'
    }
];